DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Users;

CREATE TABLE Sales
(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR                         NOT NULL,
    lastname        VARCHAR                         NOT NULL,
    age             INT CHECK (age > 0)             NOT NULL,
    purchase_item   VARCHAR                         NOT NULL,
    count           INT CHECK (count > 0)           NOT NULL,
    amount          DECIMAL(9,2) CHECK (count > 0)  NOT NULL,
    purchase_date   DATE                            NOT NULL
);

SET datestyle = "ISO, DMY";

INSERT INTO Sales (name, lastname, age, purchase_item, count, amount, purchase_date)
VALUES ('Иван', 'Иванов', 22, 'Телевизор', 1, 23000.99, '16/07/2022'),
       ('Петр', 'Петров', 18, 'Смартфон', 1, 19900.50, '17/07/2022'),
       ('Александр', 'Александров', 22, 'Соковыжималка', 1, 8900.10, '18/07/2022'),
       ('Евгений', 'Евгеньев', 18, 'Наушники', 3, 6500.20, '19/06/2022'),
       ('Юлия', 'Сергеева', 22, 'Клавиатура', 2, 4990.90, '20/05/2022'),
       ('Сергей', 'Сергеев', 18, 'Смартфон', 1, 45000.00, '21/04/2022'),
       ('Аня', 'Аннович', 34, 'Смартфон', 2, 38990.20, '22/03/2022'),
       ('Петр', 'Петров', 18, 'Наушники', 1, 11990.00, '23/02/2022');

CREATE TABLE Users(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR                 NOT NULL,
    password    VARCHAR                 NOT NULL
);

INSERT INTO Users (username, password) VALUES ('user', 'password');
