DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Users;

CREATE TABLE Sales
(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR                         NOT NULL,
    lastname        VARCHAR                         NOT NULL,
    age             INT CHECK (age > 0)             NOT NULL,
    purchase_item   VARCHAR                         NOT NULL,
    count           INT CHECK (count > 0)           NOT NULL,
    amount          DECIMAL(9,2) CHECK (count > 0)  NOT NULL,
    purchase_date   TIMESTAMP                       NOT NULL
);

CREATE TABLE Users(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR                 NOT NULL,
    password    VARCHAR                 NOT NULL
);

INSERT INTO Users (username, password) VALUES ('test_user', 'test_password');
