DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Users;

CREATE TABLE Sales
(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR                         NOT NULL,
    lastname        VARCHAR                         NOT NULL,
    age             INT CHECK (age > 0)             NOT NULL,
    count           INT CHECK (count > 0)           NOT NULL,
    amount          DECIMAL(9,2) CHECK (count > 0)  NOT NULL,
    purchase_date   DATE                            NOT NULL
);

CREATE TABLE Items
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR,
    sale_id     INT NOT NULL,
    FOREIGN KEY (sale_id) REFERENCES Sales (id) ON DELETE CASCADE
);

SET datestyle = "ISO, DMY";

INSERT INTO Sales (name, lastname, age, count, amount, purchase_date)
VALUES ('Иван', 'Иванов', 22, 1, 23000.99, '16/07/2022'),
       ('Петр', 'Петров', 18, 1, 19900.50, '17/07/2022'),
       ('Александр', 'Александров', 22, 1, 8900.10, '18/07/2022'),
       ('Евгений', 'Евгеньев', 18, 3, 6500.20, '19/06/2022'),
       ('Юлия', 'Сергеева', 22, 2, 4990.90, '20/05/2022'),
       ('Сергей', 'Сергеев', 18, 1, 45000.00, '21/04/2022');

INSERT INTO Items (name, sale_id)
VALUES ('Телевизор', 1),
       ('Смартфон', 2),
       ('Соковыжималка', 3),
       ('Наушники', 4),
       ('Клавиатура', 4),
       ('Смартфон', 4),
       ('Смартфон', 5),
       ('Смартфон', 5),
       ('Наушники', 6);

CREATE TABLE Users(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR                 NOT NULL,
    password    VARCHAR                 NOT NULL
);

INSERT INTO Users (username, password) VALUES ('user', 'password');
